name: Kappa Theta Tau
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

defaults:
  - scope:
      path: "assets/imgs/companies"
    values:
      company_image: true
